default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: squabble_development

production:
  <<: *default
  database: squabble_production

test:
  <<: *default
  database: squabble_test
